### ISSUE TITLE
Adding medRxiv?

### ISSUE THREAD

**Issue by psnavais** [dzyla/biorxiv_search#3]
Dear Dawyd,

I really like this tool that you have built for bioRxiv papers, and is my first resource to go when looking for relevant papers there. I wonder if the tool could be expanded to include medRxiv papers? 

Huge thanks!

Pol

**Comment by dzyla** [comment]
Hey Pol! 

I can have a look. Technically, I just need the API that will allow me to fetch the data from the service. I will have a look at what the medRxiv API looks like and try to implement it. Depending on the database size, it is a question whether free services will still be able to host it. Recently, I created a PubMed-based index, but due to the size restrictions, it is impossible to host it.

I am also happy the tool is useful!
best,
Dawid

**Comment by dzyla** [comment]
I have checked Medarxiv, and it is only a 50k manuscript. I already downloaded the database and calculated embeddings. Once I have the working version, I will update the GitHub repo and online services.

**Comment by dzyla** [comment]
I have updated the app and databases, and now the semantic search also includes medRxiv. Please let me know if there is anything else that would be useful!

Cheers,
Dawid
